version: "3.7"
services:
  spark-master:
    container_name: sm
    image: ajgrande924/spark-master:latest
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    environment:
      - "SPARK_LOCAL_IP=spark-master"
  spark-worker:
    container_name: sw
    image: ajgrande924/spark-worker:latest
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
  spark-submit:
    container_name: ss
    image: ajgrande924/spark-submit:latest
    depends_on:
      - spark-master
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PWD=test
    volumes:
      - ./python:/python
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
  postgres:
    image: postgres:11-alpine
    container_name: pg
    volumes:
      - ./postgres:/postgres
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: